TUMBLR_PAGE_URL           = "jpweekly.tumblr.com"
TUMBLR_CONSUMER_KEY       = ENV["TUMBLR_CONSUMER_KEY"]
TUMBLR_CONSUMER_SECRET    = ENV["TUMBLR_CONSUMER_SECRET"]
TUMBLR_OAUTH_TOKEN        = ENV["TUMBLR_OAUTH_TOKEN"]
TUMBLR_OAUTH_TOKEN_SECRET = ENV["TUMBLR_OAUTH_TOKEN_SECRET"]
