TWITTER_CONSUMER_KEY       = ENV["TWITTER_CONSUMER_KEY"]
TWITTER_CONSUMER_SECRET    = ENV["TWITTER_CONSUMER_SECRET"]
TWITTER_OAUTH_TOKEN        = ENV["TWITTER_OAUTH_TOKEN"]
TWITTER_OAUTH_TOKEN_SECRET = ENV["TWITTER_OAUTH_TOKEN_SECRET"]